# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
fr:
  languageCode: fr-fr
  contentDir: content/fr
  menu:
    main:
    - name: A propos
      url: '#about'
      weight: 10
    - name: Publications
      url: '#posts'
      weight: 20
    - name: Projets
      url: '#projects'
      weight: 30
    - name: Interventions
      url: '#talks'
      weight: 40
    - name: Travaux
      url: '#featured'
      weight: 50
    - name: Contact
      url: '#contact'
      weight: 60

  # Link to a PDF of your resume/CV from the menu.
  # To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
    - name: CV
      url: ../uploads/resume.pdf
      weight: 70